[build]
  node_bundler = "esbuild"
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.well-known/assetlinks.json"
  status = 200
  force = true